# Generated by Django 3.1 on 2020-09-29 20:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_auto_20200929_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 29, 20, 8, 51, 695656, tzinfo=utc)),
        ),
    ]
