# Generated by Django 3.1 on 2020-11-08 13:48

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_auto_20201108_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 13, 48, 1, 352492, tzinfo=utc)),
        ),
    ]
