# Generated by Django 3.1 on 2020-11-08 14:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0008_auto_20201108_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 14, 16, 3, 219594, tzinfo=utc)),
        ),
    ]
