# Generated by Django 3.1 on 2020-11-08 15:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0009_auto_20201108_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 11, 8, 15, 36, 20, 928802, tzinfo=utc)),
        ),
    ]
